services:
  fastapi:
      build:
        context: ./app
        dockerfile: Dockerfile
      container_name: fastapi
      volumes:
        - ./app:/app
        - ./data:/data
      expose:
        - "8000"
      env_file:
      - .env   
      networks:
        - appnet

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /var/www/certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - fastapi
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
