services:
  mysql:
    image: mysql:8.0
    container_name: team_activity_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: team_activities
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  fastapi:
      build:
        context: ./app
        dockerfile: Dockerfile
      container_name: team_activity_app
      volumes:
        - ./app:/app
      ports:
        - "8000:8000"
      depends_on:
        - mysql
      environment:
        - DATABASE_URL=mysql+pymysql://app_user:app_password@mysql:3306/team_activities

volumes:
  mysql_data:
