version = 4.2.0
archive_dir = /etc/letsencrypt/archive/sanseitoaichi12.f5.si
cert = /etc/letsencrypt/live/sanseitoaichi12.f5.si/cert.pem
privkey = /etc/letsencrypt/live/sanseitoaichi12.f5.si/privkey.pem
chain = /etc/letsencrypt/live/sanseitoaichi12.f5.si/chain.pem
fullchain = /etc/letsencrypt/live/sanseitoaichi12.f5.si/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 3de557a7c12326f8861fc43ffd43539c
rsa_key_size = 4096
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
